# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:


- task: CmdLine@2
  inputs:
    script: |
      ver=$(cat azure-vote/main.py | grep -E "^ver = \"[0-9.]+\"\$"|awk -F\" {'print $2'})
      echo "##vso[task.setvariable variable=version]$ver"

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub connection'
    repository: 'thjulian23/brief-8-tj-2'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: $(version)

- task: CmdLine@2
  inputs:
    script: 'sed -i ''s/{{ version }}/''$(version)''/g'' main.yml'

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'cluster-connection'
    namespace: 'qal'
    manifests: 'main.yml'

