# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub connection'
    repository: 'thjulian23/brief-8-tj'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'

- task: CmdLine@2
  inputs:
    script: 'kubectl get pods -n qal -o jsonpath="{.items[*].spec.containers[*].image}" | tr -s ''[[:space:]]'' ''\n''| sort | uniq'

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'cluster-connection'
    namespace: 'qal'
    manifests: 'main.yml'