apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp-canary
  labels:
    app: voteapplb
spec:
  selector:
    matchLabels:
      app: voteapplb
  replicas: 2
  template:
    metadata:
      labels:
        app: voteapplb
    spec:
      containers:
      - name: voteapp
        image: thjulian23/brief-8-tj-2:{{ version }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "clustredis"
        - name: STRESS_SECS
          value: "25"
