apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp-canary
  labels:
    app: voteapplb
spec:
  selector:
    matchLabels:
      app: voteapplb
  replicas: 2
  template:
    metadata:
      labels:
        app: voteapplb
    spec:
      containers:
      - name: voteapp
        image: thjulian23/brief-8-tj-2:{{ version }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "clustredis"
        - name: STRESS_SECS
          value: "25"
---
apiVersion: v1
kind: Service
metadata:
  name: loadvoteapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: voteapplb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: loadvoteapp
            port:
              number: 80
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redisstor
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: redisstor
