trigger:
- master

stages:
- stage: Build_docker_image
  displayName: 'Build_docker_image' 
  jobs:
  - job: Get_Version
    displayName: 'Get Version Build' 
    pool:
      vmImage: ubuntu-latest 
    steps:

    - task: CmdLine@2
      inputs:
        script: |
          versionnew=$(cat azure-vote/main.py | grep -E "^ver = \"[0-9.]+\"\$"|awk -F\" {'print $2'})
          versionold=$(curl -s http://votingappkube.simplon-thomas.space | grep -o 'Azure Voting App v[0-9]\+\.[0-9]\+\.[0-9]\+' | sed 's/^.*v//;s/ on.*$//' | head -n1)
          echo "##vso[task.setvariable variable=verold]$versionold"
          echo "##vso[task.setvariable variable=vernew]$versionnew"
  
    - task: Docker@2
      condition: ne(variables.verold,variables.vernew)
      inputs:
        containerRegistry: 'dockerhub connection'
        repository: 'thjulian23/brief-8-tj-2'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: 'latest'
      
    - bash: exit 1
      displayName: Fail build if partially successful
      condition: eq(variables['Agent.JobStatus'], 'SucceededWithIssues')



- stage: 'QAL_Deployment'
  dependsOn: Build_docker_image
  condition: succeeded()
  displayName: 'Deploy on QAL' 
  jobs:
  - job: 'QAL_Deploy' 
    displayName: 'Deploy on QAL' 
    pool:
      vmImage: 'ubuntu-latest' 
    steps:
    - task: KubernetesManifest@0
      name: kubeonqal
      displayName: 'kubeonqal'
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'clusterconnection'
        namespace: 'qal'
        manifests: '**/kubernetes/qal/*'
    - task: Bash@3
      name: waitingfordeploy
      inputs:
        targetType: 'inline'
        script: 'sleep 30'
      
    - task: Bash@3
      name: checksitefreevote
      displayName: Test de la requête pour voter free
      condition: succeeded()
      inputs:
        targetType: 'inline'
        script: |
          exitcode=$(curl -X POST -d "vote=free" http://qalvotingapp.simplon-thomas.space -w "%{http_code}" -o /dev/null)
          echo "##vso[task.setvariable variable=exit1]$exitcode"

    - task: Bash@3
      name: checksitem6mobilevote
      displayName: Test de la requête pour voter m6mobile
      condition: eq(variables['exit1'],'200')
      inputs:
        targetType: 'inline'
        script: |
          exitcode=$(curl -X POST -d "vote=m6mobile" http://qalvotingapp.simplon-thomas.space -w "%{http_code}" -o /dev/null)
          echo "##vso[task.setvariable variable=exit2]$exitcode"

    - task: Bash@3
      name: checksitereset
      displayName: Test de la requête pour reset
      condition: eq(variables['exit2'],'200')
      inputs:
        targetType: 'inline'
        script: |
          exitcode=$(curl -X POST -d "vote=reset" http://qalvotingapp.simplon-thomas.space -w "%{http_code}" -o /dev/null)
          echo "##vso[task.setvariable variable=exit3]$exitcode"

    - task: CmdLine@2
      name : chargetest
      displayName: Test de charge de la qal
      condition: eq(variables['exit3'],'200')
      inputs:
        script: |
          seq 250 | parallel --max-args 0  --jobs 20 "curl -k -iF 'vote=free' http://qalvotingapp.simplon-thomas.space"

    - task: CmdLine@2
      name: waitforcharge
      inputs:
        script: 'sleep 90'

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'clusterconnection'
        namespace: 'qal'
        command: 'get'
        useConfigurationFile: true
        configuration: './kubernetes/qal/qal_app.yml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
      name: qalpods

    - task: CmdLine@2
      name: countpod
      inputs:
        script: |
          qalappcount=$(echo $QALPODS_KUBECTLOUTPUT | jq '.items[0].spec.replicas')
          echo $qalappcount
          echo "##vso[task.setvariable variable=countpods]$qalappcount"

    - task: Kubernetes@1
      name: deleteqal
      condition: ne(variables['countpods'],2)
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'clusterconnection'
        namespace: 'qal'
        command: 'delete'
        arguments: '-f $(System.DefaultWorkingDirectory)/kubernetes/qal/'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
    - task: Bash@3
      name: yourverygood
      condition: succeeded()
      inputs:
        targetType: 'inline'
        script: 'echo "QAL DELETION"'


- stage: 'Deploy_canary'
  condition: succeeded() 
  displayName: 'Deploy Canary Release' 
  jobs:
  - job: 'Deploy_canary' 
    displayName: 'Deployment of Canary Release' 
    pool:
      vmImage: 'ubuntu-latest' 
    steps:
    - task: KubernetesManifest@0
      name: kubeonprodcanary
      condition: succeeded()
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'clusterconnection'
        namespace: 'prod'
        strategy: 'canary'
        percentage: '30'
        manifests: '**/kubernetes/canary/deployment-canary.yaml'

- stage: 'ManualIntervention'
  condition: succeeded() 
  displayName: 'In waiting of validation of working canary release' 
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          tjulian.ext@simplonformations.onmicrosoft.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'



- stage: 'DeployOnProd'
  displayName: 'Deploy on Prod and delete Canary' 
  jobs:
  - job: 'Deployonprod' 
    displayName: 'Deploy on Prod and delete Canary' 
    pool:
      vmImage: 'ubuntu-latest' 
    steps:

    - task: Kubernetes@1
      name: deleteprodapp
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'clusterconnection'
        namespace: 'prod'
        command: 'delete'
        arguments: '-f $(System.DefaultWorkingDirectory)/kubernetes/prod/deploy_app.yml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
      

    - task: KubernetesManifest@0
      name: kubeonprod
      condition: succeeded()
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'clusterconnection'
        namespace: 'prod'
        manifests: '**/kubernetes/prod/deploy_app.yml'

    - task: Bash@3
      name: waitingfordeploy
      inputs:
        targetType: 'inline'
        script: 'sleep 30'

    - task: Kubernetes@1
      name: deletecanary
      condition: succeeded()
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'clusterconnection'
        namespace: 'prod'
        command: 'delete'
        arguments: '-f $(System.DefaultWorkingDirectory)/kubernetes/canary/deletion-canary.yml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'

    - task: Bash@3
      name: checksitereset
      displayName: Test de la requête pour reset
      inputs:
        targetType: 'inline'
        script: |
          exitcode=$(curl -s -o -I -w "%{http_code}" http://votingappkube.simplon-thomas.space)
          echo "##vso[task.setvariable variable=exit5]$exitcode"

    - task: Bash@3
      name: yourverygood
      condition: eq(variables['exit5'],'200')
      inputs:
        targetType: 'inline'
        script: 'echo "GOOD JOB PIPELINE!"'