name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    
    runs-on: ubuntu-latest
    environment : QAL
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag az_vote_app:$(date)
    - name: see images
      run : docker images -a
